config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lands#index"
  resources :lands, except: :index
  get "platforms/decentraland" => "platforms#decentraland"
  get "platforms/thesandbox" => "platforms#thesandbox"
  get "platforms/cryptovoxels" => "platforms#cryptovoxels"
  get "platforms/somniumspace" => "platforms#somniumspace"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fee_mdy.rb
class FeeMdy < ActiveHash::Base
  self.data = [
    { id: 1, name: 'month' },
    { id: 2, name: 'day' },
    { id: 3, name: 'year' }
  ]

  include ActiveHash::Associations
  has_many :lands
  
end

app/models/land.rb
class Land < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :platform
  belongs_to :fee_mdy
  belongs_to :term_mdy

  validates :platform_id, presence: true, numericality: { other_than: 1 } 
  validates :location_x, presence: true
  validates :location_y, presence: true
  validates :fee_num, presence: true
  validates :fee_mdy_id, presence: true
  validates :term_num, presence: true
  validates :term_mdy_id, presence: true

  belongs_to :user

  has_one_attached :image
end

app/models/platform.rb
class Platform < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Decentraland' },
    { id: 3, name: 'The Sandbox' },
    { id: 4, name: 'Cryptovoxels' },
    { id: 5, name: 'Somnium Space' }
  ]

  include ActiveHash::Associations
  has_many :lands
  
end

app/models/term_mdy.rb
class TermMdy < ActiveHash::Base
  self.data = [
    { id: 1, name: 'month(s)' },
    { id: 2, name: 'day(s)' },
    { id: 3, name: 'year(s)' }
  ]

  include ActiveHash::Associations
  has_many :lands
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :lands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  before_action :move_to_index, only: [:edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
  end

  def show
    @land = Land.find(params[:id])
  end

  def new
    @land = Land.new
  end
  
  def create
    @land = Land.new(land_params)
    if @land.save
      case @land.platform_id
      when 2
        redirect_to platforms_decentraland_path
      when 3
        redirect_to platforms_thesandbox_path
      when 4
        redirect_to platforms_cryptovoxels_path
      when 5
        redirect_to platforms_somniumspace_path
      end
    else
      render :new
    end
  end

  def edit
    @land = Land.find(params[:id])
  end

  def update
    @land = Land.find(params[:id])
    if @land.update(land_params)
      redirect_to land_path(@land)
    else
      render :edit
    end
  end

  def destroy
    @land = Land.find(params[:id])
    @land.destroy
    case @land.platform_id
    when 2
      redirect_to platforms_decentraland_path
    when 3
      redirect_to platforms_thesandbox_path
    when 4
      redirect_to platforms_cryptovoxels_path
    when 5
      redirect_to platforms_somniumspace_path
    end
  end

  private
  def land_params
   params.require(:land).permit(:image, :platform_id, :location_x, :location_y, :fee_num,
                                :fee_mdy_id, :term_num, :term_mdy_id).merge(user_id: current_user.id)
  end

  def move_to_index
    @land = Land.find(params[:id])
    if user_signed_in? && current_user.id != @land.user_id
      redirect_to root_path
    end
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  def decentraland
    @lands = Land.where(platform_id: 2)
  end

  def thesandbox
    @lands = Land.where(platform_id: 3)
  end

  def cryptovoxels
    @lands = Land.where(platform_id: 4)
  end

  def somniumspace
    @lands = Land.where(platform_id: 5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/lands/edit.html.erb
<%= form_with model: @land, url: land_path, local: true do |f| %>
    <%= f.label :image %><br/>
    <%= f.file_field :image %><br/>

    <%= f.label :platform %><br/>
    <%= f.collection_select(:platform_id, Platform.all, :id, :name, {}) %><br/>

    Location<br/>
    <%= f.text_field :location_x %>
    <%= f.text_field :location_y %><br/>

    Fee<br/>
    $<%= f.text_field :fee_num %>
    /<%= f.collection_select(:fee_mdy_id, FeeMdy.all, :id, :name, {}) %><br/>

    Term<br/>
    <%= f.text_field :term_num %>
    <%= f.collection_select(:term_mdy_id, TermMdy.all, :id, :name, {}) %><br/>

    <%= f.submit "Submit" %>

<% end %>

app/views/lands/index.html.erb
<div class="index">
  <div class="index-container">

    <div class="phrase-container">
      <div class="phrase">
        Let's make effective use<br/>of metaverse lands!
      </div>
    </div>

    <div class="maps">
      <div class="index-explain">Click on the map you are interested in.</div>

      <div class="maps-container">
        <div class="slider">
          <div class="index-map">
            <li class="map-name"><%= link_to 'Decentraland', platforms_decentraland_path %></li>
            <%= link_to platforms_decentraland_path do %>
              <%= image_tag 'decentraland_map2.png', size: '450x450' %>
            <% end %>
          </div>

          <div class="index-map">
            <li class="map-name"><%= link_to 'The Sandbox', platforms_thesandbox_path %></li>
            <%= link_to platforms_thesandbox_path do %>
              <%= image_tag 'thesandbox_map2.png', size: '450x450' %>
            <% end %>
          </div>

          <div class="index-map">
            <li class="map-name"><%= link_to 'Cryptovoxels', platforms_cryptovoxels_path %></li>
            <%= link_to platforms_cryptovoxels_path do %>
              <%= image_tag 'cryptovoxels_map2.png', size: '450x450' %>
            <% end %>
          </div>

          <div class="index-map">
            <li class="map-name"><%= link_to 'Somnium Space', platforms_somniumspace_path %></li>
            <%= link_to platforms_somniumspace_path do %>
              <%= image_tag 'somniumspace_map2.png', size: '450x450' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/lands/new.html.erb
<div class="new">
  <div class="new-container">
    <%= form_with model: @land, url: lands_path, local: true do |f| %>
      <div class="form-contents">
        <div class="new-explain">Fill in information of the land.</div>
        <div class="form-content first-content">
          <div class="content-title">Image</div>
          <%= f.file_field :image %>
        </div>

        <div class="form-content">
          <div class="content-title">Platform</div>
          <%= f.collection_select(:platform_id, Platform.all, :id, :name, {}) %>
        </div>

        <div class="form-content">
          <div class="content-title">Location</div>
          <%= f.text_field :location_x %>
          <%= f.text_field :location_y %>
        </div>

        <div class="form-content">
          <div class="content-title">Fee</div>
          $<%= f.text_field :fee_num %>
          /<%= f.collection_select(:fee_mdy_id, FeeMdy.all, :id, :name, {}) %>
        </div>

        <div class="form-content">
          <div class="content-title">Term</div>
          <%= f.text_field :term_num %>
          <%= f.collection_select(:term_mdy_id, TermMdy.all, :id, :name, {}) %>
        </div>

        <div class="form-btn">
          <%= f.submit "Submit" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lands/show.html.erb
<div class="show">
  <div class="show-container">
    <div class="show-content">
      <% if @land.image.attached? %>
        <%= image_tag @land.image, size: '300x300' %>
      <% else %>
        <%= image_tag 'noimage.jpg', size: '300x300' %>
      <% end %>
    </div>

    <div class="show-content">
      Location
      <%= @land.location_x %> : <%= @land.location_y %>
    </div>

    <div class="show-content">
      Fee
      $<%= @land.fee_num %>/<%= @land.fee_mdy.name %>
    </div>

    <div class="show-content">
      Term
      <%= @land.term_num %>/<%= @land.term_mdy.name %>
    </div>

    <div class="show-content"> 
      Renter
      <%= @land.user.nickname %>
    </div>

    <% if user_signed_in? && @land.user_id == current_user.id %>
      <div class="task-btns">
        <div class="task-btn">
          <%= link_to "Edit", edit_land_path(@land), class: "show-link" %>
        </div>
        <div class="task-btn">
          <%= link_to "Remove", land_path(@land), method: :delete, class: "show-link" %>
        </div>
      </div>
    <% else %>
      <div class="contact-btn">
        <%= link_to "Contact", root_path, class: "show-link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Negotilands</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/platforms/cryptovoxels.html.erb
<div class="cryptovoxels-map">
  <div class="cryptovoxels-title">
    <%= image_tag 'https://www.esports.net/wp-content/uploads/2022/02/Cryptovoxels.jpg', size: '300x130' %>
  </div>
  <div class="cryptovoxels-new new-path">
    <%= link_to 'Will you rent your land?', new_land_path, class:"new-btn" %>
  </div>
</div>

<div class="rental-lands">
  <% if @lands.present? %>
    <% @lands.each do |land| %>
      <div class="rental-land">
        <div class="rental-land-container">
          <div class="rental-land-image rental-content">
            <%= link_to land_path(land), class:"link" do %>
              <% if land.image.attached? %>
                <%= image_tag land.image, size: '200x200' %>
              <% else%>
                <%= image_tag 'noimage.jpg', size: '200x200' %>
              <% end %>
            <% end %>
          </div>
          <div class="rental-land-location rental-content">
            Location: <%= land.location_x %>:<%= land.location_y %>
          </div>
          <div class="rental-land-fee rental-content">
            Fee: $<%= land.fee_num %>/<%= land.fee_mdy.name %>
          </div>
          <div class="rental-land-term rental-content">
            Term: <%= land.term_num %><%= land.term_mdy.name %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="no-land">
      No Rental Land
    </div>
  <% end %>
</div>

app/views/platforms/decentraland.html.erb
<div class="decentraland-map">
  <div class="decentraland-title">
    <%= image_tag 'https://bittimes.net/wp-content/uploads/2021/12/Decentraland-MANA-Logo-350.jpg', size: '300x120' %>
  </div>
  <div class="decentraland-new new-path">
    <%= link_to 'Will you rent your land?', new_land_path, class:"new-btn" %>
  </div>
</div>

<div class="rental-lands">
  <% if @lands.present? %>
    <% @lands.each do |land| %>
      <div class="rental-land">
        <div class="rental-land-container">
          <div class="rental-land-image rental-content">
            <%= link_to land_path(land), class:"link" do %>
              <% if land.image.attached? %>
                <%= image_tag land.image, size: '200x200' %>
              <% else%>
                <%= image_tag 'noimage.jpg', size: '200x200' %>
              <% end %>
            <% end %>
          </div>
          <div class="rental-land-location rental-content">
            Location: <%= land.location_x %>:<%= land.location_y %>
          </div>
          <div class="rental-land-fee rental-content">
            Fee: $<%= land.fee_num %>/<%= land.fee_mdy.name %>
          </div>
          <div class="rental-land-term rental-content">
            Term: <%= land.term_num %><%= land.term_mdy.name %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="no-land">
      No Rental Land
    </div>
  <% end %>
</div>

app/views/platforms/somniumspace.html.erb
<div class="somniumspace-map">
  <div class="somniumspace-title">
    <%= image_tag 'https://manamina.valuesccg.com/uploads/content/image/36488/5.png', size: '300x100' %>
  </div>
  <div class="somniumspace-new new-path">
    <%= link_to 'Will you rent your land?', new_land_path, class:"new-btn" %>
  </div>
</div>

<div class="rental-lands">
  <% if @lands.present? %>
    <% @lands.each do |land| %>
      <div class="rental-land">
        <div class="rental-land-container">
          <div class="rental-land-image rental-content">
            <%= link_to land_path(land), class:"link" do %>
              <% if land.image.attached? %>
                <%= image_tag land.image, size: '200x200' %>
              <% else%>
                <%= image_tag 'noimage.jpg', size: '200x200' %>
              <% end %>
            <% end %>
          </div>
          <div class="rental-land-location rental-content">
            Location: <%= land.location_x %>:<%= land.location_y %>
          </div>
          <div class="rental-land-fee rental-content">
            Fee: $<%= land.fee_num %>/<%= land.fee_mdy.name %>
          </div>
          <div class="rental-land-term rental-content">
            Term: <%= land.term_num %><%= land.term_mdy.name %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="no-land">
      No Rental Land
    </div>
  <% end %>
</div>

app/views/platforms/thesandbox.html.erb
<div class="thesandbox-map">
  <div class="thesandbox-title">
    <%= image_tag 'https://www.sandbox.game/img/01_Top_Bar/TheSandboxLogo.svg', size: '300x100' %>
  </div>
  <div class="thesandbox-new new-path">
    <%= link_to 'Will you rent your land?', new_land_path, class:"new-btn" %>
  </div>
</div>

<div class="rental-lands">
  <% if @lands.present? %>
    <% @lands.each do |land| %>
      <div class="rental-land">
        <div class="rental-land-container">
          <div class="rental-land-image rental-content">
            <%= link_to land_path(land), class:"link" do %>
              <% if land.image.attached? %>
                <%= image_tag land.image, size: '200x200' %>
              <% else%>
                <%= image_tag 'noimage.jpg', size: '200x200' %>
              <% end %>
            <% end %>
          </div>
          <div class="rental-land-location rental-content">
            Location: <%= land.location_x %>:<%= land.location_y %>
          </div>
          <div class="rental-land-fee rental-content">
            Fee: $<%= land.fee_num %>/<%= land.fee_mdy.name %>
          </div>
          <div class="rental-land-term rental-content">
            Term: <%= land.term_num %><%= land.term_mdy.name %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="no-land">
      No Rental Land
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-container">
    <div class="left-header">
      <div class="logo-name">
        <%= link_to 'Negoti Lands', root_path, class: "header-link" %>
      </div>
      <div class="logo-img">
        <%= image_tag "logo.png", size: "50x50"%>
      </div>
    </div>

    <div class="right-header">
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "link" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "link" %>
        <%= link_to 'Signup', new_user_registration_path, class: "link" %>
      <% end %>
    </div>
  </div>
</div>